name: Docker Build Devop Test

on:
  push:
    branches: [devop]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Iniciando el proceso de build para el API..."
      # (Pasos de build aquí)
      - run: echo "✅ API compilada exitosamente."

  build-web:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🌐 Iniciando el proceso de build para el Frontend Web..."
      # (Pasos de build aquí)
      - run: echo "✅ Web compilada exitosamente."

  trigger-deploy:
    needs: [build-api, build-web]
    # Se pasan automáticamente SNYK_TOKEN, TELEGRAM_TOKEN_PROD, etc.
    uses: ./.github/workflows/deploy.yml
    secrets: inherit