name: Deploy and Security Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Desplegando i/api:production..."
      # (Pasos de deploy aquí)
      - run: echo "✅ API en producción."

  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🌐 Desplegando Frontend..."
      # (Pasos de deploy aquí)
      - run: echo "✅ Frontend en producción."

  snyk-security:
    needs: [deploy-api, deploy-web]
    # Al usar inherit, el workflow de Snyk recibirá los 4 secretos definidos
    uses: ./.github/workflows/snyk-test.yml
    secrets: inherit