name: Deploy and Security Pipeline

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true
        description: 'Snyk authentication token'
      SNYK_ORG_ID:
        required: false
        description: 'Snyk organization ID'
      TELEGRAM_TOKEN_PROD:
        required: false
        description: 'Telegram bot token'
      TELEGRAM_CHAT_PROD:
        required: false
        description: 'Telegram chat ID'


jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Desplegando i/api:production..."
      # (Pasos de deploy aquí)
      - run: echo "✅ API en producción."

  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🌐 Desplegando Frontend..."
      # (Pasos de deploy aquí)
      - run: echo "✅ Frontend en producción."

  snyk-security:
    needs: [deploy-api, deploy-web]
    # Al usar inherit, el workflow de Snyk recibirá los 4 secretos definidos
    uses: ./.github/workflows/snyk-test.yml
    secrets: inherit